By: Luis Gonzalez
Create an ANN for a simple classification.
Building a simple 2 layer ANN

In [119]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import OneHotEncoder
df = pd.read_csv('IRIS.csv')
df

sepal_length  sepal_width  petal_length  petal_width         species
0             5.1          3.5           1.4          0.2     Iris-setosa
1             4.9          3.0           1.4          0.2     Iris-setosa
2             4.7          3.2           1.3          0.2     Iris-setosa
3             4.6          3.1           1.5          0.2     Iris-setosa
4             5.0          3.6           1.4          0.2     Iris-setosa
..            ...          ...           ...          ...             ...
145           6.7          3.0           5.2          2.3  Iris-virginica
146           6.3          2.5           5.0          1.9  Iris-virginica
147           6.5          3.0           5.2          2.0  Iris-virginica
148           6.2          3.4           5.4          2.3  Iris-virginica
149           5.9          3.0           5.1          1.8  Iris-virginica

[150 rows x 5 columns]

In [ ]:
X = df.drop('species', axis=1)
y = df['species']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

print(X_train.shape)
print(X_test.shape)
print(y_train.shape)
print(y_test.shape)


(105, 4)
(45, 4)
(105,)
(45,)


In [103]:
X_train.shape

(105, 4)

Features = corresponds to the number of neurons at the input layer
Hidden layer = corresponds to the computation of y = z = 1/1+e^(W*X+b)
*The number of layers is proportional to the difficulty of your problem
*Choosing the hidden later nodes rule of thumb
The number of hidden neurons shouwl be between the size of the input layer and the size of the output layer.
The number of hidden neurons should be 2/3 the size of the input layer, plut the size of the output layer.


In [ ]:
def calculate_z(w, x, b):
    return np.dot(w,x) + b

def relu(z):
    return np.maximum(0, z)

def softmax(z):
    return np.exp(z)/np.sum(np.exp(z))

def sigmoid_derivative(x):
    return x * (1 - x)
    
def sigmoid(z):
    return 1/ (1 + (np.exp(-z)))

def forward_prop(w1, b1, w2, b2, x):
    z1 = np.dot(w1, x) + b1
    a1 = sigmoid(z1)
    z2 = np.dot(w2, a1) + b2
    a2 = softmax(z2)
    return z1,a1,z2, a2

def back_prop(y, a1, z2, a2, w2):
    m = y.size
    dz2 = a2 - y
    dw2 = 1/(m*np.dot(dz2,a1))
    return


SyntaxError: invalid syntax (2307843811.py, line 26)

In [124]:
def init_params():
    w1 = np.random.randn(4, 105)
    b1 = np.random.randn(4,1)
    w2 = np.random.randn(4,4)
    b2 = np.random.randn(4,1)
    return w1,b1,w2,b2

w1, b1, w2, b2 = init_params()

In [125]:
def gradient_descent(X, Y, iterations, alpha):
    w1, b1, w2, b2 = init_params()
    z1, a1, z2, a2 = forward_prop(w1, b1, w2,b2, X)
    print(a2)
    
    

gradient_descent(X_train, y_train, 50, 0.1)

[[0.02608953 0.02616861 0.01402666 0.01404759]
 [0.00691477 0.00694578 0.00083544 0.00083908]
 [0.0029607  0.00296599 0.00399632 0.0039951 ]
 [0.29063317 0.29069924 0.15435211 0.15452992]]
